[package]
name = "prop-check-rs"
version = "0.1.0"
authors = ["Junichi Kato <j5ik2o@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.1" }
once_cell = "1.5.2"
bigdecimal = "0.2.0"
iso-4217 = "0.1"
num-bigint = "0.3"
rust-fp-categories = "0.0.5"
futures = { verison = "0.3.1", features = ["thread-pool"] }
# tokio = { version = "1", features = ["full"] }
itertools = "0.10.0"
