[package]
name = "prop-check-rs"
version = "0.0.121"
authors = ["Junichi Kato <j5ik2o@gmail.com>"]
description = "A Property-based testing Library in Rust"
repository="https://github.com/j5ik2o/prop-check-rs"
readme = "./README.md"
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["testing", "property-based"]

[badges]
github = { repository = "j5ik2o/prop-check-rs", workflow = "ci" }

[features]
bigint = ["dep:num-bigint"]
bigdecimal = ["dep:bigdecimal"]

[dependencies]
log = "0.4.17"
rand = "0.8.5"
itertools = "0.10.5"
anyhow = "1.0.69"
num-traits = "0.2.15"

bigdecimal = { version = "0.3.0", optional = true }
num-bigint = { version = "0.4", optional = true }

[dev-dependencies]
env_logger = "0.10.0"
ctor = "0.1.26"
